// Global Constants
export const CHATHUB_AUTH_DETAILS = "CHATHUB_AUTH_DETAILS";

// Window Height Constants
export const CHANGE_WINDOW_HEIGHT = "CHANGE_WINDOW_HEIGHT";
export const WINDOW_HEIGHT_CHANGED = "WINDOW_HEIGHT_CHANGED";

// Auth Constants
export const AUTH_SIGNUP_REQUEST = "AUTH_SIGNUP_REQUEST";
export const AUTH_LOGIN_REQUEST = "AUTH_LOGIN_REQUEST";
export const AUTH_SIGNUP_RESPONSE = "AUTH_SIGNUP_RESPONSE";
export const AUTH_LOGIN_RESPONSE = "AUTH_LOGIN_RESPONSE";
export const AUTH_RESET_ERRORS = "AUTH_RESET_ERRORS";
export const AUTH_UPDATE_ERRORS = "AUTH_UPDATE_ERRORS";

export const AUTH_LOADING_TOGGLE = "AUTH_LOADING_TOGGLE";
export const UPDATE_AUTH_DETAILS = "UPDATE_AUTH_DETAILS";
